version: '3'
services:
  php:
    container_name: php-apache22
    build: .
    volumes:
      - ./public_html/:/var/www/html/
    ports:
      - 9600:80
    depends_on:
      - db
  db:
    container_name: mysql22
    image: mysql:5.7.40
    environment:
      MYSQL_ROOT_PASSWORD: 1234
      MYSQL_DATABASE: db_test
      MYSQL_USER: mysql
      MYSQL_PASSWORD: 1234
    ports:
      - "3306:3306"
